version: '3.2'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  phoenix:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on: 
      - db
    environment:
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      GUARDIAN_SECRET_KEY: ${GUARDIAN_SECRET_KEY}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    command:
      - ./prod_entrypoint.sh
volumes:
  pgdata: