version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  phoenix:
    build:
      context: .
    environment:
      DB_PORT: 5432
      DB_NAME: tfcon_dev
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    depends_on: 
      - db
  
volumes:
  pgdata: