version: '3.2'

services:
  db:
    image: postgres:9.6
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_DB: ${DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
  
  phoenix:
    image: egustavos/tfcon:deploy0
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on: 
      - db
    environment:
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      GUARDIAN_SECRET_KEY: ${GUARDIAN_SECRET_KEY}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    command:
      - ./prod_entrypoint.sh
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata: